package com.ddky.im.communityeconomy;

public class LongMessageConst {

    public static final String[] longMessages = {
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "I Think, this is very strong project","I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀","Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "Keep working hard and don't ever surrender, To the moon!!",
            "Amazing project and management work keep going great work ❤️",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon🔥",
            "Great project and best DEVs","Great project and best DEVs",
            "Hi sir great project and TO THE MOON🚀","Hi sir great project and TO THE MOON🚀",
            "Hi Admin, I want to say thank you for your hard work. I hope this project will be success and the development team will go the moon",
            "Your project is amazing. You have a great Team and strong Community, I am very impressed",
            "Best of luck for this project..",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀",
            "This project is looks so innovative and impactful, happy to take participate in such huge project. You guys are very hard working and I am pretty sure you will reach to the Moon very soon.",
            "I really like this project. The project has developed strongly and is on track. I always support the project for the continuation of the future",
            "This project looks very interesting. I am interested, and I will support this project until it is successful according to the plan that has been set",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Hello friends.\n" +
                    "Good project, please support. I hope it has a good future and we will all benefit together\n" +
                    "Of course, it goes without saying that you should always enter projects with research and be successful.",
            "This project is very good, so hopefully the project will be better in the future and the cryptocurrency will be the best.",
            "Big thanks for PROJECTNAME family",
            "WOW\n" +
                    "A very nice project for everyone\n" +
                    "So let's make it a success together and get comfortable investing",
            "This project looks very interesting. I am interested, and I will support this project until it is successful. Thanks a lot",
            "Really love to see the community growing \uD83D\uDCAA Let’s go!",
            "I am sp proud to be here . What a wonderfull project",
            "moon soon \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\n" +
                    "☁️☁️ ☁️                  \uD83C\uDF14     ☁️\n" +
                    "            ☁️ ☁️    \uD83D\uDE80\n" +
                    "   ☁️                *       ☁️ \n" +
                    "                    *  \n" +
                    "      ☁️     * \n" +
                    "               *     \n" +
                    "             * \n" +
                    "            *    \n" +
                    "           *\n" +
                    "         \uD83D\uDCA5\n" +
                    "         \uD83C\uDF0E\n" +
                    " \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80Lets go!",
            "They are doing an amazing job",
            "A friend of mine told me about this project yesterday",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "/WE_ARE_STRONG",
            "/WE_ARE_STRONG",
            "Sure\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF",
            "Sure\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF",
            "Sure\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF",
            "Sure\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF",
            "Sure\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF",
            "Hey new members \uD83D\uDC4B\uD83C\uDFFB\n" +
                    "\n" +
                    "Welcome to PROJECTNAME Official Chat\n" +
                    " telegram group\uD83D\uDD25\n" +
                    "\n" +
                    "\n" +
                    "No Spam Links \uD83D\uDC4E\n" +
                    "No Advertising \uD83D\uDEAB\n" +
                    "\n" +
                    "\uD83D\uDCCC\uD83D\uDCCC Please read pinned messages for latest updates\uD83D\uDCCC\uD83D\uDCCC\n" +
                    "|\uD83D\uDCE3\uD83D\uDCE3I like to share this when people are new\uD83D\uDCE3\uD83D\uDCE3",
            "Hey new members \uD83D\uDC4B\uD83C\uDFFB\n" +
                    "\n" +
                    "Welcome to PROJECTNAME Official Chat\n" +
                    " telegram group\uD83D\uDD25\n" +
                    "\n" +
                    "\n" +
                    "No Spam Links \uD83D\uDC4E\n" +
                    "No Advertising \uD83D\uDEAB\n" +
                    "\n" +
                    "\uD83D\uDCCC\uD83D\uDCCC Please read pinned messages for latest updates\uD83D\uDCCC\uD83D\uDCCC\n" +
                    "|\uD83D\uDCE3\uD83D\uDCE3I like to share this when people are new\uD83D\uDCE3\uD83D\uDCE3",
            "Hey new members \uD83D\uDC4B\uD83C\uDFFB\n" +
                    "\n" +
                    "Welcome to PROJECTNAME Official Chat\n" +
                    " telegram group\uD83D\uDD25\n" +
                    "\n" +
                    "\n" +
                    "No Spam Links \uD83D\uDC4E\n" +
                    "No Advertising \uD83D\uDEAB\n" +
                    "\n" +
                    "\uD83D\uDCCC\uD83D\uDCCC Please read pinned messages for latest updates\uD83D\uDCCC\uD83D\uDCCC\n" +
                    "|\uD83D\uDCE3\uD83D\uDCE3I like to share this when people are new\uD83D\uDCE3\uD83D\uDCE3",
            "Hey new members \uD83D\uDC4B\uD83C\uDFFB\n" +
                    "\n" +
                    "Welcome to PROJECTNAME Official Chat\n" +
                    " telegram group\uD83D\uDD25\n" +
                    "\n" +
                    "\n" +
                    "No Spam Links \uD83D\uDC4E\n" +
                    "No Advertising \uD83D\uDEAB\n" +
                    "\n" +
                    "\uD83D\uDCCC\uD83D\uDCCC Please read pinned messages for latest updates\uD83D\uDCCC\uD83D\uDCCC\n" +
                    "|\uD83D\uDCE3\uD83D\uDCE3I like to share this when people are new\uD83D\uDCE3\uD83D\uDCE3",
            "Mooning things on board flying to the moon\uD83D\uDE80\uD83D\uDE80",
            "Mooning things on board flying to the moon\uD83D\uDE80\uD83D\uDE80",
            "Mooning things on board flying to the moon\uD83D\uDE80\uD83D\uDE80",
            "Mooning things on board flying to the moon\uD83D\uDE80\uD83D\uDE80",
            "/contract","/contract","/contract","/contract","/contract","/contract","/contract","/contract","/contract",
            "\uD83D\uDC46\uD83D\uDC46\uD83D\uDC46\uD83D\uDC46\uD83D\uDC46\uD83D\uDE80","\uD83D\uDC46\uD83D\uDC46\uD83D\uDC46\uD83D\uDC46\uD83D\uDC46\uD83D\uDE80","\uD83D\uDC46\uD83D\uDC46\uD83D\uDC46\uD83D\uDC46\uD83D\uDC46\uD83D\uDE80",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "I Think, this is very strong project","I Think, this is very strong project","I Think, this is very strong project","I Think, this is very strong project",
            "I Think, this is very strong project","I Think, this is very strong project","I Think, this is very strong project","I Think, this is very strong project",
            "This project looks very interesting. I am interested, and I will support this project until it is successful. Thanks a lot","This project looks very interesting. I am interested, and I will support this project until it is successful. Thanks a lot",
            "This project looks very interesting. I am interested, and I will support this project until it is successful. Thanks a lot","This project looks very interesting. I am interested, and I will support this project until it is successful. Thanks a lot",
            "This project looks very interesting. I am interested, and I will support this project until it is successful. Thanks a lot","This project looks very interesting. I am interested, and I will support this project until it is successful. Thanks a lot",
            "Really love to see the community growing! Let's go!","Really love to see the community growing! Let's go!","Really love to see the community growing! Let's go!",
            "Really love to see the community growing! Let's go!","Really love to see the community growing! Let's go!","Really love to see the community growing! Let's go!",
            "I am sp proud to be here . What a wonderfull project","I am sp proud to be here . What a wonderfull project","I am sp proud to be here . What a wonderfull project",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon\uD83D\uDE80",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon\uD83D\uDE80",
            "This project is looks so innovative and impactful, happy to take participate in such huge project. You guys are very hard working and I am pretty sure you will reach to the Moon very soon.",
            "This project is looks so innovative and impactful, happy to take participate in such huge project. You guys are very hard working and I am pretty sure you will reach to the Moon very soon.",
            "I really like this project. The project has developed strongly and is on track. I always support the project for the continuation of the future",
            "I really like this project. The project has developed strongly and is on track. I always support the project for the continuation of the future",
            "I really like this project. The project has developed strongly and is on track. I always support the project for the continuation of the future",
            "This project looks very interesting. I am interested, and I will support this project until it is successful according to the plan that has been set",
            "This project looks very interesting. I am interested, and I will support this project until it is successful according to the plan that has been set",
            "This project looks very interesting. I am interested, and I will support this project until it is successful according to the plan that has been set",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Hello friends","Hello friends","Hello friends","Hello friends","Hello friends","Hello friends","Hello friends","Hello friends","Hello friends","Hello friends",
            "Hello friends","Hello friends","Hello friends","Hello friends","Hello friends","Hello friends","Hello friends","Hello friends","Hello friends","Hello friends",
            "/WE_ARE_STRONG","/WE_ARE_STRONG","/WE_ARE_STRONG","/WE_ARE_STRONG","/WE_ARE_STRONG","/WE_ARE_STRONG",
            "/PROJECTNAME_IS_THE_BEST","/PROJECTNAME_IS_THE_BEST","/PROJECTNAME_IS_THE_BEST","/PROJECTNAME_IS_THE_BEST","/PROJECTNAME_IS_THE_BEST","/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST","/PROJECTNAME_IS_THE_BEST","/PROJECTNAME_IS_THE_BEST","/PROJECTNAME_IS_THE_BEST","/PROJECTNAME_IS_THE_BEST","/PROJECTNAME_IS_THE_BEST",
            "/price@DexTools_Pricebot","/price@DexTools_Pricebot","/price@DexTools_Pricebot","/price@DexTools_Pricebot","/price@DexTools_Pricebot","/price@DexTools_Pricebot",
            "Great project","Great project","Great project",
            "/LET_GET_MORE_BAG","/LET_GET_MORE_BAG","/LET_GET_MORE_BAG","/LET_GET_MORE_BAG","/LET_GET_MORE_BAG","/LET_GET_MORE_BAG","/LET_GET_MORE_BAG","/LET_GET_MORE_BAG","/LET_GET_MORE_BAG",
            "To the fucking moon guys\uD83D\uDD25","To the fucking moon guys\uD83D\uDD25","To the fucking moon guys\uD83D\uDD25","To the fucking moon guys\uD83D\uDD25","To the fucking moon guys\uD83D\uDD25","To the fucking moon guys\uD83D\uDD25",
            "Keep working hard and don't ever surrender, To the moon!!","Keep working hard and don't ever surrender, To the moon!!","Keep working hard and don't ever surrender, To the moon!!","Keep working hard and don't ever surrender, To the moon!!","Keep working hard and don't ever surrender, To the moon!!",
            "Keep working hard and don't ever surrender, To the moon!!","Keep working hard and don't ever surrender, To the moon!!","Keep working hard and don't ever surrender, To the moon!!","Keep working hard and don't ever surrender, To the moon!!","Keep working hard and don't ever surrender, To the moon!!",
            "Amazing project and management work keep going great work ❤️","Amazing project and management work keep going great work ❤️","Amazing project and management work keep going great work ❤️","Amazing project and management work keep going great work ❤️",
            "Amazing project and management work keep going great work ❤️","Amazing project and management work keep going great work ❤️","Amazing project and management work keep going great work ❤️","Amazing project and management work keep going great work ❤️",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon\uD83D\uDD25",
            "Great project and best DEVs\",\"Great project and best DEVs","Great project and best DEVs\",\"Great project and best DEVs","Great project and best DEVs\",\"Great project and best DEVs","Great project and best DEVs\",\"Great project and best DEVs",
            "moon soon \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\n" +
                    "☁️☁️ ☁️                  \uD83C\uDF14     ☁️\n" +
                    "            ☁️ ☁️    \uD83D\uDE80\n" +
                    "   ☁️                *       ☁️ \n" +
                    "                    *  \n" +
                    "      ☁️     * \n" +
                    "               *     \n" +
                    "             * \n" +
                    "            *    \n" +
                    "           *\n" +
                    "         \uD83D\uDCA5\n" +
                    "         \uD83C\uDF0E\n" +
                    " \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80Lets go!",
            "moon soon \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\n" +
                    "☁️☁️ ☁️                  \uD83C\uDF14     ☁️\n" +
                    "            ☁️ ☁️    \uD83D\uDE80\n" +
                    "   ☁️                *       ☁️ \n" +
                    "                    *  \n" +
                    "      ☁️     * \n" +
                    "               *     \n" +
                    "             * \n" +
                    "            *    \n" +
                    "           *\n" +
                    "         \uD83D\uDCA5\n" +
                    "         \uD83C\uDF0E\n" +
                    " \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80Lets go!",
            "moon soon \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\n" +
                    "☁️☁️ ☁️                  \uD83C\uDF14     ☁️\n" +
                    "            ☁️ ☁️    \uD83D\uDE80\n" +
                    "   ☁️                *       ☁️ \n" +
                    "                    *  \n" +
                    "      ☁️     * \n" +
                    "               *     \n" +
                    "             * \n" +
                    "            *    \n" +
                    "           *\n" +
                    "         \uD83D\uDCA5\n" +
                    "         \uD83C\uDF0E\n" +
                    " \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80Lets go!",
            "Yes bro we're all ready bro this project belong to us bro",
            "Yes bro we're all ready bro this project belong to us bro",
            "Yes bro we're all ready bro this project belong to us bro",
            "Let's keep going for \n" +
                    "The PROJECTNAME is boiling","Let's keep going for \n" +
            "The PROJECTNAME is boiling","Let's keep going for \n" +
            "The PROJECTNAME is boiling","Let's keep going for \n" +
            "The PROJECTNAME is boiling",
            "Come get yous",
"Kindly read pinned message first will help you know more about PROJECTNAME",
"Hey",
"/PROJECTNAME_IS_THE_BEST",
"I Think, this is very strong project",
"Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/PROJECTNAME_IS_THE_BEST",
"That's right guys tell everyone about this awesome project" +
    "Because we're all ready to invest",
            "Together we can achieve great things",
"Yes, so hot here",
"/price@DexTools_Pricebot",
"Maybe moooooooooooooooooon soon!",
            "Kindly stay tuned for official announcement",
"What an amazing project",
"ok, thx for all the information admin ✨",
            "I Think, this is very strong project",
"Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Lambo 🔜🔜🔜🔜",
            "Hahaha, really!",
            "I want lambo, but I believe in this project",
"Yes bro! You should hold 100 $PROJECTNAME and add liquidity! The best token.",
"Great project",
"/PROJECTNAME_IS_THE_BEST",
"Keep working hard and don't ever surrender, To the moon!!",
            "Hi sir great project and TO THE MOON🚀","Hi sir great project and TO THE MOON🚀",
"Hi Admin, I want to say thank you for your hard work. I hope this project will be success and the development team will go the moon",
"Your project is amazing. You have a great Team and strong Community, I am very impressed",
"Best of luck for this project.",
            "Amazing project and management work keep going great work ❤️",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon🔥",
            "Great project and best DEVs","Great project and best DEVs",
"/PROJECTNAME_IS_THE_BEST",
"Kindly read pinned message first will help you know more about PROJECTNAME",
"/WE_ARE_STRONG",
"/WE_ARE_STRONG",
"Let's pump this project guy's",
"This project is gonna moon hard guys trust us",
"Welcome to PROJECTNAME",
"/contract",
"Make sure you invite all investors you to PROJECTNAME",
"Hi",
"/PROJECTNAME_IS_THE_BEST",
"/PROJECTNAME_IS_THE_BEST",
"/PROJECTNAME_IS_THE_BEST",
"Welcome bro!",
            "/PROJECTNAME_IS_THE_BEST",
"/PROJECTNAME_IS_THE_BEST",
"Hey",
"Hi everyone",
"a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀🚀🚀",
            "/PROJECTNAME_IS_THE_BEST",
"/PROJECTNAME_IS_THE_BEST",
"/PROJECTNAME_IS_THE_BEST",
"/PROJECTNAME_IS_THE_BEST",
"It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "I Think, this is very strong project",
"Hello to you all",
"/PROJECTNAME_IS_THE_BEST",
"/PROJECTNAME_IS_THE_BEST",
"/PROJECTNAME_IS_THE_BEST",
"Hey",
"I like this great project",
"/LET_GET_MORE_BAG",
"/LET_GET_MORE_BAG",
"/LET_GET_MORE_BAG",
"I Think, this is very strong project",
"Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/LET_GET_MORE_BAG",
"/LET_GET_MORE_BAG",
"Hahaha",
"Yes mate",
"/contract",
"All new members are welcome please go through pinned messages and visit website to know more about group:)",
            "I had told my dad to buy $PROJECTNAME",
"Really great",
"/LET_GET_MORE_BAG",
"/LET_GET_MORE_BAG",
"/LET_GET_MORE_BAG",
"/LET_GET_MORE_BAG",
"/price@DexTools_Pricebot",
"/LET_GET_MORE_BAG",
"We have come to fly\n" +
    "To conquer obstacles\n"+
    "To win now\n"+
    "Let's go to the moon 🌕\n"+
            "🚀🚀🚀🚀🚀🚀🚀🚀",
            "Hey",
"Good project, please support.",
"I hope it has a good future and we will all benefit together",
"Of course, it goes without saying that you should always enter projects with research and be successful.",
            "This project is very good, so hopefully the project will be better in the future and the cryptocurrency will be the best.",
"Big thanks for PROJECTNAME family",
"WOW\n" +
    "A very nice project for everyone\n"+
    "So let's make it a success together and get comfortable investing",
            "Hi everyone",
"a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀",
            "This project is looks so innovative and impactful, happy to take participate in such huge project. You guys are very hard working and I am pretty sure you will reach to the Moon very soon.",
"I really like this project. The project has developed strongly and is on track. I always support the project for the continuation of the future",
"This project looks very interesting. I am interested, and I will support this project until it is successful according to the plan that has been set",
"It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Hello friends.",
    "Keep the investors coming this project project is awesome truly awesome",
            "Amazing project and management work keep going great work ❤️👍😊",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon",
            "Great project and best DEVs",
            "LET'S GO GUYSS!! LET'S KEEP THE POSITIVE VIBES HERE!!🔥🔥",
            "Hi",
"Yes, the best team and the best token",
"Okay let show the world what' we have here",
            "Hi",
            "We have come to fly",
    "Conquer obstacle",
"This is project bullish",
"That's right guys tell everyone about this awesome project\n"+
    "Because we're all ready to invest\n"+
    "Let fucking go to the moon\n"+
"💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯",
        "Hello.\n"+
    "Tell more investors like me about PROJECTNAME knoww when launch",
"Yep, I love it too",
"Just stay tuned bro, admin will announce here soon",
"Okay, bro! Thx",
"Do we have any plan about listing on cex!",
            "I love this project",
"Sure, you can read pinned message! It's better to read whitepaper.",
            "Got it!",
            "This is project bullish",

"Hhhhh. Yes mate. I ready for it. And wish to win whitelist.",
"You need to complete the task bro.",
"Hahahaha, of course, I have done it.",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "Hey",
            "/PROJECTNAME_IS_THE_BEST",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/PROJECTNAME_IS_THE_BEST",
            "That's right guys tell everyone about this awesome project" +
                    "Because we're all ready to invest",
            "Together we can achieve great things",
            "Yes, so hot here",
            "/price@DexTools_Pricebot",
            "Maybe moooooooooooooooooon soon!",
            "Kindly stay tuned for official announcement",
            "What an amazing project",
            "ok, thx for all the information admin ✨",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Lambo 🔜🔜🔜🔜",
            "Hahaha, really!",
            "I want lambo, but I believe in this project",
            "Yes bro! You should hold 100 $PROJECTNAME and add liquidity! The best token.",
            "Great project",
            "/PROJECTNAME_IS_THE_BEST",
            "Keep working hard and don't ever surrender, To the moon!!",
            "Hi sir great project and TO THE MOON🚀","Hi sir great project and TO THE MOON🚀",
            "Hi Admin, I want to say thank you for your hard work. I hope this project will be success and the development team will go the moon",
            "Your project is amazing. You have a great Team and strong Community, I am very impressed",
            "Best of luck for this project.",
            "Amazing project and management work keep going great work ❤️",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon🔥",
            "Great project and best DEVs","Great project and best DEVs",
            "/PROJECTNAME_IS_THE_BEST",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "/WE_ARE_STRONG",
            "/WE_ARE_STRONG",
            "Let's pump this project guy's",
            "This project is gonna moon hard guys trust us",
            "Welcome to PROJECTNAME",
            "/contract",
            "Make sure you invite all investors you to PROJECTNAME",
            "Hi",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Welcome bro!",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Hey",
            "Hi everyone",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀🚀🚀",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "I Think, this is very strong project",
            "Hello to you all",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Hey",
            "I like this great project",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "Hahaha",
            "Yes mate",
            "/contract",
            "All new members are welcome please go through pinned messages and visit website to know more about group:)",
            "I had told my dad to buy $PROJECTNAME",
            "Really great",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/price@DexTools_Pricebot",
            "/LET_GET_MORE_BAG",
            "We have come to fly\n" +
                    "To conquer obstacles\n"+
                    "To win now\n"+
                    "Let's go to the moon 🌕\n"+
                    "🚀🚀🚀🚀🚀🚀🚀🚀",
            "Hey",
            "Good project, please support.",
            "I hope it has a good future and we will all benefit together",
            "Of course, it goes without saying that you should always enter projects with research and be successful.",
            "This project is very good, so hopefully the project will be better in the future and the cryptocurrency will be the best.",
            "Big thanks for PROJECTNAME family",
            "WOW\n" +
                    "A very nice project for everyone\n"+
                    "So let's make it a success together and get comfortable investing",
            "Hi everyone",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀",
            "This project is looks so innovative and impactful, happy to take participate in such huge project. You guys are very hard working and I am pretty sure you will reach to the Moon very soon.",
            "I really like this project. The project has developed strongly and is on track. I always support the project for the continuation of the future",
            "This project looks very interesting. I am interested, and I will support this project until it is successful according to the plan that has been set",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Hello friends.",
            "Keep the investors coming this project project is awesome truly awesome",
            "Amazing project and management work keep going great work ❤️👍😊",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon",
            "Great project and best DEVs",
            "LET'S GO GUYSS!! LET'S KEEP THE POSITIVE VIBES HERE!!🔥🔥",
            "Hi",
            "Yes, the best team and the best token",
            "Okay let show the world what' we have here",
            "Hi",
            "We have come to fly",
            "Conquer obstacle",
            "This is project bullish",
            "That's right guys tell everyone about this awesome project\n"+
                    "Because we're all ready to invest\n"+
                    "Let fucking go to the moon\n"+
                    "💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯",
            "Hello.\n"+
                    "Tell more investors like me about PROJECTNAME knoww when launch",
            "Yep, I love it too",
            "Just stay tuned bro, admin will announce here soon",
            "Okay, bro! Thx",
            "Do we have any plan about listing on cex!",
            "I love this project",
            "Sure, you can read pinned message! It's better to read whitepaper.",
            "Got it!",
            "This is project bullish",

            "Hhhhh. Yes mate. I ready for it. And wish to win whitelist.",
            "You need to complete the task bro.",
            "Hahahaha, of course, I have done it.",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "Hey",
            "/PROJECTNAME_IS_THE_BEST",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/PROJECTNAME_IS_THE_BEST",
            "That's right guys tell everyone about this awesome project" +
                    "Because we're all ready to invest",
            "Together we can achieve great things",
            "Yes, so hot here",
            "/price@DexTools_Pricebot",
            "Maybe moooooooooooooooooon soon!",
            "Kindly stay tuned for official announcement",
            "What an amazing project",
            "ok, thx for all the information admin ✨",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Lambo 🔜🔜🔜🔜",
            "Hahaha, really!",
            "I want lambo, but I believe in this project",
            "Yes bro! You should hold 100 $PROJECTNAME and add liquidity! The best token.",
            "Great project",
            "/PROJECTNAME_IS_THE_BEST",
            "Keep working hard and don't ever surrender, To the moon!!",
            "Hi sir great project and TO THE MOON🚀","Hi sir great project and TO THE MOON🚀",
            "Hi Admin, I want to say thank you for your hard work. I hope this project will be success and the development team will go the moon",
            "Your project is amazing. You have a great Team and strong Community, I am very impressed",
            "Best of luck for this project.",
            "Amazing project and management work keep going great work ❤️",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon🔥",
            "Great project and best DEVs","Great project and best DEVs",
            "/PROJECTNAME_IS_THE_BEST",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "/WE_ARE_STRONG",
            "/WE_ARE_STRONG",
            "Let's pump this project guy's",
            "This project is gonna moon hard guys trust us",
            "Welcome to PROJECTNAME",
            "/contract",
            "Make sure you invite all investors you to PROJECTNAME",
            "Hi",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Welcome bro!",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Hey",
            "Hi everyone",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀🚀🚀",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "I Think, this is very strong project",
            "Hello to you all",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Hey",
            "I like this great project",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "Hahaha",
            "Yes mate",
            "/contract",
            "All new members are welcome please go through pinned messages and visit website to know more about group:)",
            "I had told my dad to buy $PROJECTNAME",
            "Really great",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/price@DexTools_Pricebot",
            "/LET_GET_MORE_BAG",
            "We have come to fly\n" +
                    "To conquer obstacles\n"+
                    "To win now\n"+
                    "Let's go to the moon 🌕\n"+
                    "🚀🚀🚀🚀🚀🚀🚀🚀",
            "Hey",
            "Good project, please support.",
            "I hope it has a good future and we will all benefit together",
            "Of course, it goes without saying that you should always enter projects with research and be successful.",
            "This project is very good, so hopefully the project will be better in the future and the cryptocurrency will be the best.",
            "Big thanks for PROJECTNAME family",
            "WOW\n" +
                    "A very nice project for everyone\n"+
                    "So let's make it a success together and get comfortable investing",
            "Hi everyone",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀",
            "This project is looks so innovative and impactful, happy to take participate in such huge project. You guys are very hard working and I am pretty sure you will reach to the Moon very soon.",
            "I really like this project. The project has developed strongly and is on track. I always support the project for the continuation of the future",
            "This project looks very interesting. I am interested, and I will support this project until it is successful according to the plan that has been set",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Hello friends.",
            "Keep the investors coming this project project is awesome truly awesome",
            "Big opportunity to meet you at the best of the project is really fantastic project very good project.",
            "Amazing project and management work keep going great work ❤️👍😊",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon",
            "Great project and best DEVs",
            "LET'S GO GUYSS!! LET'S KEEP THE POSITIVE VIBES HERE!!🔥🔥",
            "Hi",
            "Yes, the best team and the best token",
            "Okay let show the world what' we have here",
            "Hi",
            "We have come to fly",
            "Conquer obstacle",
            "This is project bullish",
            "That's right guys tell everyone about this awesome project\n"+
                    "Because we're all ready to invest\n"+
                    "Let fucking go to the moon\n"+
                    "💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯",
            "Hello.\n"+
                    "Tell more investors like me about PROJECTNAME knoww when launch",
            "Yep, I love it too",
            "Just stay tuned bro, admin will announce here soon",
            "Okay, bro! Thx",
            "Do we have any plan about listing on cex!",
            "I love this project",
            "Sure, you can read pinned message! It's better to read whitepaper.",
            "Got it!",
            "This is project bullish",

            "Hhhhh. Yes mate. I ready for it. And wish to win whitelist.",
            "You need to complete the task bro.",
            "Hahahaha, of course, I have done it.",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "Hey",
            "/PROJECTNAME_IS_THE_BEST",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/PROJECTNAME_IS_THE_BEST",
            "That's right guys tell everyone about this awesome project" +
                    "Because we're all ready to invest",
            "Together we can achieve great things",
            "Yes, so hot here",
            "/price@DexTools_Pricebot",
            "Maybe moooooooooooooooooon soon!",
            "Kindly stay tuned for official announcement",
            "What an amazing project",
            "ok, thx for all the information admin ✨",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Lambo 🔜🔜🔜🔜",
            "Hahaha, really!",
            "I want lambo, but I believe in this project",
            "Yes bro! You should hold 100 $PROJECTNAME and add liquidity! The best token.",
            "Great project",
            "/PROJECTNAME_IS_THE_BEST",
            "Keep working hard and don't ever surrender, To the moon!!",
            "Hi sir great project and TO THE MOON🚀","Hi sir great project and TO THE MOON🚀",
            "Nice project and Hopefully to the moon and getting better",
            "Hi Admin, I want to say thank you for your hard work. I hope this project will be success and the development team will go the moon",
            "Your project is amazing. You have a great Team and strong Community, I am very impressed",
            "Best of luck for this project.",
            "Big opportunity to meet you at the best of the project is really fantastic project very good project.",
            "Amazing project and management work keep going great work ❤️",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon🔥",
            "Great project and best DEVs","Great project and best DEVs",
            "/PROJECTNAME_IS_THE_BEST",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "/WE_ARE_STRONG",
            "/WE_ARE_STRONG",
            "Let's pump this project guy's",
            "This project is gonna moon hard guys trust us",
            "Welcome to PROJECTNAME",
            "/contract",
            "Make sure you invite all investors you to PROJECTNAME",
            "Hi",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Welcome bro!",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Hey",
            "Hi everyone",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀🚀🚀",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "I Think, this is very strong project",
            "Hello to you all",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Hey",
            "I like this great project",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "Hahaha",
            "Yes mate",
            "/contract",
            "All new members are welcome please go through pinned messages and visit website to know more about group:)",
            "I had told my dad to buy $PROJECTNAME",
            "Really great",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/price@DexTools_Pricebot",
            "/LET_GET_MORE_BAG",
            "We have come to fly\n" +
                    "To conquer obstacles\n"+
                    "To win now\n"+
                    "Let's go to the moon 🌕\n"+
                    "🚀🚀🚀🚀🚀🚀🚀🚀",
            "Hey",
            "Good project, please support.",
            "I hope it has a good future and we will all benefit together",
            "Of course, it goes without saying that you should always enter projects with research and be successful.",
            "This project is very good, so hopefully the project will be better in the future and the cryptocurrency will be the best.",
            "Big thanks for PROJECTNAME family",
            "WOW\n" +
                    "A very nice project for everyone\n"+
                    "So let's make it a success together and get comfortable investing",
            "Hi everyone",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀",
            "This project is looks so innovative and impactful, happy to take participate in such huge project. You guys are very hard working and I am pretty sure you will reach to the Moon very soon.",
            "I really like this project. The project has developed strongly and is on track. I always support the project for the continuation of the future",
            "This project looks very interesting. I am interested, and I will support this project until it is successful according to the plan that has been set",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Hello friends.",
            "Keep the investors coming this project project is awesome truly awesome",
            "Big opportunity to meet you at the best of the project is really fantastic project very good project.",
            "Amazing project and management work keep going great work ❤️👍😊",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon",
            "Great project and best DEVs",
            "LET'S GO GUYSS!! LET'S KEEP THE POSITIVE VIBES HERE!!🔥🔥",
            "Hi",
            "Yes, the best team and the best token",
            "Okay let show the world what' we have here",
            "Hi",
            "We have come to fly",
            "Conquer obstacle",
            "This is project bullish",
            "That's right guys tell everyone about this awesome project\n"+
                    "Because we're all ready to invest\n"+
                    "Let fucking go to the moon\n"+
                    "💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯",
            "Hello.\n"+
                    "Tell more investors like me about PROJECTNAME knoww when launch",
            "Yep, I love it too",
            "Just stay tuned bro, admin will announce here soon",
            "Okay, bro! Thx",
            "Do we have any plan about listing on cex!",
            "I love this project",
            "Sure, you can read pinned message! It's better to read whitepaper.",
            "Got it!",
            "This is project bullish",

            "Hhhhh. Yes mate. I ready for it. And wish to win whitelist.",
            "You need to complete the task bro.",
            "Hahahaha, of course, I have done it.",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "Hey",
            "/PROJECTNAME_IS_THE_BEST",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/PROJECTNAME_IS_THE_BEST",
            "That's right guys tell everyone about this awesome project" +
                    "Because we're all ready to invest",
            "Together we can achieve great things",
            "Yes, so hot here",
            "/price@DexTools_Pricebot",
            "Maybe moooooooooooooooooon soon!",
            "Kindly stay tuned for official announcement",
            "What an amazing project",
            "ok, thx for all the information admin ✨",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Lambo 🔜🔜🔜🔜",
            "Hahaha, really!",
            "I want lambo, but I believe in this project",
            "Yes bro! You should hold 100 $PROJECTNAME and add liquidity! The best token.",
            "Great project",
            "/PROJECTNAME_IS_THE_BEST",
            "Keep working hard and don't ever surrender, To the moon!!",
            "Hi sir great project and TO THE MOON🚀","Hi sir great project and TO THE MOON🚀",
            "Nice project and Hopefully to the moon and getting better",
            "Hi Admin, I want to say thank you for your hard work. I hope this project will be success and the development team will go the moon",
            "Your project is amazing. You have a great Team and strong Community, I am very impressed",
            "Best of luck for this project.",
            "Big opportunity to meet you at the best of the project is really fantastic project very good project.",
            "Amazing project and management work keep going great work ❤️",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon🔥",
            "Great project and best DEVs","Great project and best DEVs",
            "/PROJECTNAME_IS_THE_BEST",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "/WE_ARE_STRONG",
            "/WE_ARE_STRONG",
            "Let's pump this project guy's",
            "This project is gonna moon hard guys trust us",
            "Welcome to PROJECTNAME",
            "/contract",
            "Make sure you invite all investors you to PROJECTNAME",
            "Hi",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Welcome bro!",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Hey",
            "Hi everyone",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀🚀🚀",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "I Think, this is very strong project",
            "Hello to you all",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Hey",
            "I like this great project",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "Hahaha",
            "Yes mate",
            "/contract",
            "All new members are welcome please go through pinned messages and visit website to know more about group:)",
            "I had told my dad to buy $PROJECTNAME",
            "Really great",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/price@DexTools_Pricebot",
            "/LET_GET_MORE_BAG",
            "We have come to fly\n" +
                    "To conquer obstacles\n"+
                    "To win now\n"+
                    "Let's go to the moon 🌕\n"+
                    "🚀🚀🚀🚀🚀🚀🚀🚀",
            "Hey",
            "Good project, please support.",
            "I hope it has a good future and we will all benefit together",
            "Of course, it goes without saying that you should always enter projects with research and be successful.",
            "This project is very good, so hopefully the project will be better in the future and the cryptocurrency will be the best.",
            "Big thanks for PROJECTNAME family",
            "WOW\n" +
                    "A very nice project for everyone\n"+
                    "So let's make it a success together and get comfortable investing",
            "Hi everyone",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀",
            "This project is looks so innovative and impactful, happy to take participate in such huge project. You guys are very hard working and I am pretty sure you will reach to the Moon very soon.",
            "I really like this project. The project has developed strongly and is on track. I always support the project for the continuation of the future",
            "This project looks very interesting. I am interested, and I will support this project until it is successful according to the plan that has been set",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Hello friends.",
            "Keep the investors coming this project project is awesome truly awesome",
            "Big opportunity to meet you at the best of the project is really fantastic project very good project.",
            "Amazing project and management work keep going great work ❤️👍😊",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon",
            "Great project and best DEVs",
            "LET'S GO GUYSS!! LET'S KEEP THE POSITIVE VIBES HERE!!🔥🔥",
            "Hi",
            "Yes, the best team and the best token",
            "Okay let show the world what' we have here",
            "Hi",
            "We have come to fly",
            "Conquer obstacle",
            "This is project bullish",
            "That's right guys tell everyone about this awesome project\n"+
                    "Because we're all ready to invest\n"+
                    "Let fucking go to the moon\n"+
                    "💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯",
            "Hello.\n"+
                    "Tell more investors like me about PROJECTNAME knoww when launch",
            "Yep, I love it too",
            "Just stay tuned bro, admin will announce here soon",
            "Okay, bro! Thx",
            "Do we have any plan about listing on cex!",
            "I love this project",
            "Sure, you can read pinned message! It's better to read whitepaper.",
            "Got it!",
            "This is project bullish",

            "Hhhhh. Yes mate. I ready for it. And wish to win whitelist.",
            "You need to complete the task bro.",
            "Hahahaha, of course, I have done it.",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "Hey",
            "/PROJECTNAME_IS_THE_BEST",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/PROJECTNAME_IS_THE_BEST",
            "That's right guys tell everyone about this awesome project" +
                    "Because we're all ready to invest",
            "Together we can achieve great things",
            "Yes, so hot here",
            "/price@DexTools_Pricebot",
            "Maybe moooooooooooooooooon soon!",
            "Kindly stay tuned for official announcement",
            "What an amazing project",
            "ok, thx for all the information admin ✨",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Lambo 🔜🔜🔜🔜",
            "Hahaha, really!",
            "I want lambo, but I believe in this project",
            "Yes bro! You should hold 100 $PROJECTNAME and add liquidity! The best token.",
            "Great project",
            "/PROJECTNAME_IS_THE_BEST",
            "Keep working hard and don't ever surrender, To the moon!!",
            "Hi sir great project and TO THE MOON🚀","Hi sir great project and TO THE MOON🚀",
            "Nice project and Hopefully to the moon and getting better",
            "Hi Admin, I want to say thank you for your hard work. I hope this project will be success and the development team will go the moon",
            "Your project is amazing. You have a great Team and strong Community, I am very impressed",
            "Best of luck for this project.",
            "Big opportunity to meet you at the best of the project is really fantastic project very good project.",
            "Amazing project and management work keep going great work ❤️",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon🔥",
            "Great project and best DEVs","Great project and best DEVs",
            "/PROJECTNAME_IS_THE_BEST",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "/WE_ARE_STRONG",
            "/WE_ARE_STRONG",
            "Let's pump this project guy's",
            "This project is gonna moon hard guys trust us",
            "Welcome to PROJECTNAME",
            "/contract",
            "Make sure you invite all investors you to PROJECTNAME",
            "Hi",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Welcome bro!",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Hey",
            "Hi everyone",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀🚀🚀",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "I Think, this is very strong project",
            "Hello to you all",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Hey",
            "I like this great project",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "Hahaha",
            "Yes mate",
            "/contract",
            "All new members are welcome please go through pinned messages and visit website to know more about group:)",
            "I had told my dad to buy $PROJECTNAME",
            "Really great",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/price@DexTools_Pricebot",
            "/LET_GET_MORE_BAG",
            "We have come to fly\n" +
                    "To conquer obstacles\n"+
                    "To win now\n"+
                    "Let's go to the moon 🌕\n"+
                    "🚀🚀🚀🚀🚀🚀🚀🚀",
            "Hey",
            "Good project, please support.",
            "I hope it has a good future and we will all benefit together",
            "Of course, it goes without saying that you should always enter projects with research and be successful.",
            "This project is very good, so hopefully the project will be better in the future and the cryptocurrency will be the best.",
            "Big thanks for PROJECTNAME family",
            "WOW\n" +
                    "A very nice project for everyone\n"+
                    "So let's make it a success together and get comfortable investing",
            "Hi everyone",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀",
            "This project is looks so innovative and impactful, happy to take participate in such huge project. You guys are very hard working and I am pretty sure you will reach to the Moon very soon.",
            "I really like this project. The project has developed strongly and is on track. I always support the project for the continuation of the future",
            "This project looks very interesting. I am interested, and I will support this project until it is successful according to the plan that has been set",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Hello friends.",
            "Keep the investors coming this project project is awesome truly awesome",
            "Big opportunity to meet you at the best of the project is really fantastic project very good project.",
            "Amazing project and management work keep going great work ❤️👍😊",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon",
            "Great project and best DEVs",
            "LET'S GO GUYSS!! LET'S KEEP THE POSITIVE VIBES HERE!!🔥🔥",
            "Hi",
            "Yes, the best team and the best token",
            "Okay let show the world what' we have here",
            "Hi",
            "We have come to fly",
            "Conquer obstacle",
            "This is project bullish",
            "That's right guys tell everyone about this awesome project\n"+
                    "Because we're all ready to invest\n"+
                    "Let fucking go to the moon\n"+
                    "💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯",
            "Hello.\n"+
                    "Tell more investors like me about PROJECTNAME knoww when launch",
            "Yep, I love it too",
            "Just stay tuned bro, admin will announce here soon",
            "Okay, bro! Thx",
            "Do we have any plan about listing on cex!",
            "I love this project",
            "Sure, you can read pinned message! It's better to read whitepaper.",
            "Got it!",
            "This is project bullish",

            "Hhhhh. Yes mate. I ready for it. And wish to win whitelist.",
            "You need to complete the task bro.",
            "Hahahaha, of course, I have done it.",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "Hey",
            "/PROJECTNAME_IS_THE_BEST",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/PROJECTNAME_IS_THE_BEST",
            "That's right guys tell everyone about this awesome project" +
                    "Because we're all ready to invest",
            "Together we can achieve great things",
            "Yes, so hot here",
            "/price@DexTools_Pricebot",
            "Maybe moooooooooooooooooon soon!",
            "Kindly stay tuned for official announcement",
            "What an amazing project",
            "ok, thx for all the information admin ✨",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Lambo 🔜🔜🔜🔜",
            "Hahaha, really!",
            "I want lambo, but I believe in this project",
            "Yes bro! You should hold 100 $PROJECTNAME and add liquidity! The best token.",
            "Great project",
            "/PROJECTNAME_IS_THE_BEST",
            "Keep working hard and don't ever surrender, To the moon!!",
            "Hi sir great project and TO THE MOON🚀","Hi sir great project and TO THE MOON🚀",
            "Nice project and Hopefully to the moon and getting better",
            "Hi Admin, I want to say thank you for your hard work. I hope this project will be success and the development team will go the moon",
            "Your project is amazing. You have a great Team and strong Community, I am very impressed",
            "Best of luck for this project.",
            "Big opportunity to meet you at the best of the project is really fantastic project very good project.",
            "Amazing project and management work keep going great work ❤️",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon🔥",
            "Great project and best DEVs","Great project and best DEVs",
            "/PROJECTNAME_IS_THE_BEST",
            "Kindly read pinned message first will help you know more about PROJECTNAME",
            "/WE_ARE_STRONG",
            "/WE_ARE_STRONG",
            "Let's pump this project guy's",
            "This project is gonna moon hard guys trust us",
            "Welcome to PROJECTNAME",
            "/contract",
            "Make sure you invite all investors you to PROJECTNAME",
            "Hi",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Welcome bro!",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Hey",
            "Hi everyone",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀🚀🚀",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "I Think, this is very strong project",
            "Hello to you all",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "/PROJECTNAME_IS_THE_BEST",
            "Hey",
            "I like this great project",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "I Think, this is very strong project",
            "Thanks for shared this wonderful opportunity🚀",
            "Best wishes for all team members🙏🙏🙏🙏🙏",
            "Wish all the best for developer and all team project, I hope you're all still healthy and I believe your project will success.",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "Hahaha",
            "Yes mate",
            "/contract",
            "All new members are welcome please go through pinned messages and visit website to know more about group:)",
            "I had told my dad to buy $PROJECTNAME",
            "Really great",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/LET_GET_MORE_BAG",
            "/price@DexTools_Pricebot",
            "/LET_GET_MORE_BAG",
            "We have come to fly\n" +
                    "To conquer obstacles\n"+
                    "To win now\n"+
                    "Let's go to the moon 🌕\n"+
                    "🚀🚀🚀🚀🚀🚀🚀🚀",
            "Hey",
            "Good project, please support.",
            "I hope it has a good future and we will all benefit together",
            "Of course, it goes without saying that you should always enter projects with research and be successful.",
            "This project is very good, so hopefully the project will be better in the future and the cryptocurrency will be the best.",
            "Big thanks for PROJECTNAME family",
            "WOW\n" +
                    "A very nice project for everyone\n"+
                    "So let's make it a success together and get comfortable investing",
            "Hi everyone",
            "a project that looks very good, may this project always be a success and be a guide for investing in the future. cheers to the team on this excellent project, and will fly to the moon🚀",
            "This project is looks so innovative and impactful, happy to take participate in such huge project. You guys are very hard working and I am pretty sure you will reach to the Moon very soon.",
            "I really like this project. The project has developed strongly and is on track. I always support the project for the continuation of the future",
            "This project looks very interesting. I am interested, and I will support this project until it is successful according to the plan that has been set",
            "It's a good project. I really appreciate it, I will support you till the end, hope your project will go to the moon in the future and believe it. I am Glad to be participant.",
            "Hello friends.",
            "Keep the investors coming this project project is awesome truly awesome",
            "Big opportunity to meet you at the best of the project is really fantastic project very good project.",
            "Amazing project and management work keep going great work ❤️👍😊",
            "PROJECTNAME is a unique project and it's going to be at the top notch soon",
            "Great project and best DEVs",
            "LET'S GO GUYSS!! LET'S KEEP THE POSITIVE VIBES HERE!!🔥🔥",
            "Hi",
            "Yes, the best team and the best token",
            "Okay let show the world what' we have here",
            "Hi",
            "We have come to fly",
            "Conquer obstacle",
            "This is project bullish",
            "That's right guys tell everyone about this awesome project\n"+
                    "Because we're all ready to invest\n"+
                    "Let fucking go to the moon\n"+
                    "💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯💯",
            "Hello.\n"+
                    "Tell more investors like me about PROJECTNAME knoww when launch",
            "Yep, I love it too",
            "Just stay tuned bro, admin will announce here soon",
            "Okay, bro! Thx",
            "Do we have any plan about listing on cex!",
            "I love this project",
            "Sure, you can read pinned message! It's better to read whitepaper.",
            "Got it!",
            "This is project bullish",

            "Hhhhh. Yes mate. I ready for it. And wish to win whitelist.",
            "You need to complete the task bro.",
            "Hahahaha, of course, I have done it.",
            "\uD83D\uDD25PROJECTNAME is committed to becoming the next epoch-making decentralized / community-driven DAO platform ecosystem.\n" +
                    "Bringing Crypto to the World! A Diverse DeFi Ecosystem.\n" +
                    "Swap, earn, farm, and launch your projects, powered by DeFi.",
            "PROJECTNAME coming!\uD83D\uDD25\n" +
                    "PROJECTNAME is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Binance Network. \n" +
                    "The goal is to provide a comprehensive and convenient, one-stop platform for the cryptocurrency community.",
            "\uD83D\uDD25PROJECTNAME is committed to becoming the next epoch-making decentralized / community-driven DAO platform ecosystem.\n" +
                    "Bringing Crypto to the World! A Diverse DeFi Ecosystem.\n" +
                    "Swap, earn, farm, and launch your projects, powered by DeFi.",
            "PROJECTNAME coming!\uD83D\uDD25\n" +
                    "PROJECTNAME is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Binance Network. \n" +
                    "The goal is to provide a comprehensive and convenient, one-stop platform for the cryptocurrency community.",
            "\uD83D\uDD25PROJECTNAME is committed to becoming the next epoch-making decentralized / community-driven DAO platform ecosystem.\n" +
                    "Bringing Crypto to the World! A Diverse DeFi Ecosystem.\n" +
                    "Swap, earn, farm, and launch your projects, powered by DeFi.",
            "PROJECTNAME coming!\uD83D\uDD25\n" +
                    "PROJECTNAME is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Binance Network. \n" +
                    "The goal is to provide a comprehensive and convenient, one-stop platform for the cryptocurrency community.",
            "\uD83D\uDD25PROJECTNAME is committed to becoming the next epoch-making decentralized / community-driven DAO platform ecosystem.\n" +
                    "Bringing Crypto to the World! A Diverse DeFi Ecosystem.\n" +
                    "Swap, earn, farm, and launch your projects, powered by DeFi.",
            "PROJECTNAME coming!\uD83D\uDD25\n" +
                    "PROJECTNAME is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Binance Network. \n" +
                    "The goal is to provide a comprehensive and convenient, one-stop platform for the cryptocurrency community.",
            "\uD83D\uDD25PROJECTNAME is committed to becoming the next epoch-making decentralized / community-driven DAO platform ecosystem.\n" +
                    "Bringing Crypto to the World! A Diverse DeFi Ecosystem.\n" +
                    "Swap, earn, farm, and launch your projects, powered by DeFi.",
            "PROJECTNAME coming!\uD83D\uDD25\n" +
                    "PROJECTNAME is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Binance Network. \n" +
                    "The goal is to provide a comprehensive and convenient, one-stop platform for the cryptocurrency community.",
            "\uD83D\uDD25PROJECTNAME is committed to becoming the next epoch-making decentralized / community-driven DAO platform ecosystem.\n" +
                    "Bringing Crypto to the World! A Diverse DeFi Ecosystem.\n" +
                    "Swap, earn, farm, and launch your projects, powered by DeFi.",
            "PROJECTNAME coming!\uD83D\uDD25\n" +
                    "PROJECTNAME is a decentralized exchange, providing liquidity and enabling peer-to-peer transactions on the Binance Network. \n" +
                    "The goal is to provide a comprehensive and convenient, one-stop platform for the cryptocurrency community."
    };
}
