spring:
    application:
        name: fangjia-eureka-client-slave1
    profiles:
        active: slave1
    security:
#        user:
#            name: eureka-client
#            password: 123456
eureka:
    instance:
        hostname: fangjia-eureka-client-slave1
        status-page-url: http://${eureka.instance.hostname}:${server.port}/swagger-ui.html

#management:
#    endpoints:
#        web:
#            exposure:
#                include: "*"
#            cors:
#                allowed-origins: "*"
#                allowed-methods: "*"