package com.ddky.im.dreamdao;

public class LinkMessageConst {

    public static final String[] linkMessage = {
            "https://t.me/DreamDAOAnnouncement/29",
            "https://t.me/DreamDAOAnnouncement/27",
            "https://t.me/DreamDAOAnnouncement/26",
            "https://t.me/DreamDAOAnnouncement/25",
            "https://t.me/DreamDAOAnnouncement/18",
            "https://t.me/DreamDAOAnnouncement/18",
            "https://t.me/DreamDAOAnnouncement/18",
            "https://t.me/DreamDAOAnnouncement/18",
            "https://t.me/DreamDAOAnnouncement/18",
            "https://t.me/DreamDAOAnnouncement/18",
            "https://t.me/DreamDAOAnnouncement/18",
            "https://t.me/DreamDAOAnnouncement/16",
            "https://t.me/DreamDAOAnnouncement/12",
            "https://t.me/DreamDAOAnnouncement/12",
            "https://t.me/DreamDAOAnnouncement/12",
            "https://t.me/DreamDAOAnnouncement/12",
            "https://t.me/DreamDAOAnnouncement/12",
            "https://t.me/DreamDAOAnnouncement/12",
            "https://t.me/DreamDAOAnnouncement/12",
            "https://t.me/DreamDAOAnnouncement/11",
            "https://t.me/DreamDAOAnnouncement/11",
            "https://t.me/DreamDAOAnnouncement/11",
            "https://t.me/DreamDAOAnnouncement/10",
            "https://t.me/DreamDAOAnnouncement/10",
            "https://t.me/DreamDAOAnnouncement/10",
            "https://t.me/DreamDAOAnnouncement/10",
            "https://t.me/DreamDAOAnnouncement/10",
            "https://t.me/DreamDAOAnnouncement/10",
            "https://t.me/DreamDAOAnnouncement/10",
            "https://t.me/DreamDAOAnnouncement/10",
            "https://t.me/DreamDAOAnnouncement/7",
            "https://t.me/DreamDAOAnnouncement/7",
            "https://t.me/DreamDAOAnnouncement/7",
            "https://t.me/DreamDAOAnnouncement/7",
            "https://t.me/DreamDAOAnnouncement/7",
            "https://t.me/DreamDAOAnnouncement/7",
            "https://t.me/DreamDAOAnnouncement/7",
            "https://t.me/DreamDAOAnnouncement/7",
            "https://t.me/DreamDAOAnnouncement/7",
            "https://t.me/DreamDAOAnnouncement/3",
            "https://t.me/DreamDAOAnnouncement/3",
            "https://t.me/DreamDAOAnnouncement/3"
    };
}
