package com.ddky.im.dreamdao;

public class WelcomeCommonMessageConst {

    public static final String[] WelcomeCommonMessages = {
            "Welcome to PROJECTNAME community","Welcome to PROJECTNAME community","Welcome to PROJECTNAME community","Welcome to PROJECTNAME community",
            "Welcome to home", "Welcome bro", "Welcome you all","Welcome to home", "Welcome bro", "Welcome you all",
            "Yeah let’s MOON",
            "Welcome to PROJECTNAME\n" + "Keep the investors coming this project project is awesome truly awesome",
            "Welcome to PROJECTNAME\n" + "Keep the investors coming this project project is awesome truly awesome",
            "Hello.\n" + "Tell more investors like me about PROJECTNAME",
            "Make sure you invite all investors you to PROJECTNAME",
            "Tell more investors that here is only were we all can invest freely without fear",
            "Hello to you all","Hello to you all","Hello to you all","Hello to you all","Hello to you all","Hello to you all","Hello to you all",
            "Hello to you all","Hello to you all","Hello to you all","Hello to you all","Hello to you all","Hello to you all","Hello to you all",
            "Hello.\n" + "Tell more investors like me about PROJECTNAME",
            "Hello.\n" + "Tell more investors like me about PROJECTNAME",
            "Hello.\n" + "Tell more investors like me about PROJECTNAME",
            "Yeah feel free to invest here PROJECTNAME has brought the good news to for we all",
            "Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello",
            "Welcome to home","Welcome to home","Welcome to home","Welcome to home",
            "Welcome to family","Welcome to family","Welcome to family", "Welcome to family",
            "More investors like me are still coming",
            "This is our home",
            "Hi", "Hi", "Hi", "Hi", "Hi","Hi", "Hi", "Hi", "Hi", "Hi","Hi", "Hi", "Hi", "Hi", "Hi","Hi", "Hi", "Hi", "Hi", "Hi",
            "Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir",
            "Welcome to home", "Welcome bro", "Welcome you all","Welcome to home", "Welcome bro", "Welcome you all",
            "You damn right mate  this project is really expressing me",
            "LET'S GO GUYSS!! LET'S KEEP THE POSITIVE VIBES HERE!!\uD83D\uDD25\uD83D\uDD25",
            "That's right guys tell everyone about this awesome project\n" + "Because we're all ready to invest",
            "Thank God for PROJECTNAME","Thank God for PROJECTNAME","Thank God for PROJECTNAME","Thank God for PROJECTNAME","Thank God for PROJECTNAME",
            "Sure bro am ready for the good news\n" + "Because the good news is huge",
            "Hi", "Hi", "Hi", "Hi", "Hi","Hi", "Hi", "Hi", "Hi", "Hi","Hi", "Hi", "Hi", "Hi", "Hi","Hi", "Hi", "Hi", "Hi", "Hi",
            "I say to you all PROJECTNAME makes history . Amazing Devs and Team and sick Project with NFT is Dope",
            "Come and have yours\n" + "PROJECTNAME has made it so simple it is all",
            "Come and have yours\n" + "PROJECTNAME has made it so simple it is all",
            "Hi", "Hi", "Hi", "Hi", "Hi","Hi", "Hi", "Hi", "Hi", "Hi","Hi", "Hi", "Hi", "Hi", "Hi","Hi", "Hi", "Hi", "Hi", "Hi",
            "Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello","Hello",
            "Wow that is great \n" + "Big bro PROJECTNAME made it easy for each and every one of us bro",
            "This is GODS given opportunity for all of us guys","This is GODS given opportunity for all of us guys","This is GODS given opportunity for all of us guys",
            "I can't wait to invest mine",
            "This perfect opportunity for us all",
            "Invest here and remained bless all your life",
            "Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all",
            "I swear PROJECTNAME makes history after thw start and listening . Crazy men",
            "This really a big deal",
            "Thanks mate. Please keep supporting PROJECTNAME team","Thanks mate. Please keep supporting PROJECTNAME team","Thanks mate. Please keep supporting PROJECTNAME team",
            "Stay tuned for the good news","Stay tuned for the good news","Stay tuned for the good news","Stay tuned for the good news",
            "Make sure you come with your families and friends for this wonderful opportunity",
            "Welcome to PROJECTNAME family",
            "A friend of mine told me about this project yesterday",
            "Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all","Hi all",
            "Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir",
            "Do you know when airdrop will happen?\n" +
                    "Is there a deadline?",
            "great project","great project","great project","great project","great project","great project",
            "Nice","Nice","Nice","Nice","Nice","Nice Project","Nice Project","Nice Project","Nice Project","Nice Project",
            "I like this project","I like this project","I like this project","I like this project","I like this project","I like this project","I like this project",
            "Very strong project","Very strong project","Very strong project","Very strong project","Very strong project","Very strong project","Very strong project",
            "Hi", "Hi", "Hi", "Hi", "Hi","Hi", "Hi", "Hi", "Hi", "Hi","Hi", "Hi", "Hi", "Hi", "Hi","Hi", "Hi", "Hi", "Hi", "Hi",
            "Is the bull market coming?",
            "Hi everyone, thanks for management\uD83D\uDE4F",
            "This was a great & excellent project & also the reward is great. Thanks for share this wonderful opportunity. Best whises for all team members. Keep going and get to the success.",
            "Very well. Thanks",
            "Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir","Hi, sir",
            "At first thanks to all of you sir for this nice project. I love this airdrop. I wish I could win here. Take my love and best regards❤️",
            "Don't worry ,my brother will pick u up",
            "Great thanks! Excited to be here",
            "Thanks for having me!",
            "Thank you sir for giving us such a great opportunity. I am supporting  it always. Succus for the development projects till to the monn \uD83D\uDE4F\uD83D\uDE4F\uD83D\uDE4F\uD83D\uDE4F",
    };
}
