server:
  port: 8777
spring:
  application:
    name: fangjia-user
  zipkin:
    base-url: http://fangjia-zipkin:9411
eureka:
  instance:
    hostname: fangjia-user
  client:
    service-url:
      defaultZone: http://fangjia-eureka-server:8761/eureka/
feign:
  hystrix:
    enabled: true