package com.ddky.im.poldaswap;

public class NiceMessageConst {

    public static final String[] niceMessages = {
            "Nice", "Nice work", "Nice team", "Nice project", "Nice community", "TO-THE-MOON", "This project is gonna moon hard guys trust us",
            "Let's pump this project guy's","Let's pump this project guy's","Let's pump this project guy's","Let's pump this project guy's","Let's pump this project guy's",
            "Okay let show the world what' we have here",
            "This is a great opportunity for we investors",
            "We have come to fly\n" + "Conquer obstacle \n" + "Let fucking go to the moon",
            "Nice to have you onboard sir! Fasten your seat belt",
            "Let fucking goooooooooooooo","Let fucking goooooooooooooo","Let fucking goooooooooooooo","Let fucking goooooooooooooo","Let fucking goooooooooooooo","Let fucking goooooooooooooo",
            "Sure is the real one mate invest without fear",
            "Let's pump this project guy's","Let's pump this project guy's","Let's pump this project guy's","Let's pump this project guy's","Let's pump this project guy's",
            "Let's pump this project guy's","Let's pump this project guy's","Let's pump this project guy's","Let's pump this project guy's","Let's pump this project guy's",
            "PROJECTNAME is always the best...","PROJECTNAME is always the best...","PROJECTNAME is always the best...","PROJECTNAME is always the best...","PROJECTNAME is always the best...",
            "WE ARE THE BEST","WE ARE THE BEST","WE ARE THE BEST","WE ARE THE BEST","WE ARE THE BEST","WE ARE THE BEST","WE ARE THE BEST","WE ARE THE BEST",
            "WE ARE STRONG","WE ARE STRONG","WE ARE STRONG","WE ARE STRONG","WE ARE STRONG","WE ARE STRONG","WE ARE STRONG","WE ARE STRONG",
            "Investors keep on coming we're all here for you all",
            "Nice", "Nice work", "Nice team", "Nice project", "Nice community","Nice", "Nice work", "Nice team", "Nice project", "Nice community","Nice", "Nice work", "Nice team", "Nice project", "Nice community",
            "Let's keep going for \n" + "The PROJECTNAME is boiling","Let's keep going for \n" + "The PROJECTNAME is boiling","Let's keep going for \n" + "The PROJECTNAME is boiling",
            "Hahaha sure dear this project is our we're all here to invest I'm coming along with my friend Edwin and modwatt",
            "Nice", "Nice work", "Nice team", "Nice project", "Nice community", "TO-THE-MOON", "This project is gonna moon hard guys trust us",
            "Lambo","LMAO","Lambo","LMAO","Lambo","LMAO","Lambo","LMAO","Lambo","LMAO","Lambo","LMAO",
            "LOL","LOL","LOL","LOL","LOL","LOL","LOL","LOL",
            "I Think, this is very strong project", "Thanks for shared this wonderful opportunity",
            "Best wishes for all team members \uD83D\uDC4D\uD83D\uDE80","Best wishes for all team members \uD83D\uDC4D\uD83D\uDE80",
            "That's why I told my dad about this project and even my dad's friends",
            "What an amazing project","What an amazing project","What an amazing project","What an amazing project","What an amazing project","What an amazing project",
            "Together we can achieve great things",
            "Nice", "Nice work", "Nice team", "Nice project", "Nice community","Nice", "Nice work", "Nice team", "Nice project", "Nice community","Nice", "Nice work", "Nice team", "Nice project", "Nice community",
            "Nice", "Nice work", "Nice team", "Nice project", "Nice community", "TO-THE-MOON","Nice", "Nice work", "Nice team", "Nice project",
            "To the mooooooooooon", "To the moon","To the mooooooooooon", "To the moon","To the mooooooooooon", "To the moon","To the mooooooooooon", "To the moon",
            "Tell mummy dad uncle aunt brother's sister's about this great project \n" + "That PROJECTNAME is always on top",
            "Let’s keep shilling","Let’s keep shilling","Let’s keep shilling","Let’s keep shilling","Let’s keep shilling",
            "Hello every one of investors this is great opportunity to grab yours",
            "That's right Guy's this is for real the one and only project",
            "Hey", "Hey", "Hey", "Hey","Hey", "Hey", "Hey", "Hey","Hey", "Hey", "Hey", "Hey","Hey", "Hey", "Hey", "Hey","Hey", "Hey", "Hey",
            "Guys take off the astronaut helmet, we will go to the moon!!!!",
            "Make sure you grab your own opportunity guys","Make sure you grab your own opportunity guys",
            "Opportunity comes but once","Opportunity comes but once",
            "Keep coming guys","Keep coming guys","Keep coming guys","Keep coming guys","Keep coming guys","Keep coming guys",
            "Call your families and friends this is a wonderful opportunity",
            "For more information kindly go through pinned messages","For more information kindly go through pinned messages","For more information kindly go through pinned messages",
            "For more information kindly go through pinned messages","For more information kindly go through pinned messages","For more information kindly go through pinned messages",
            "moon soon \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\n" + "☁️☁️ ☁️                  \uD83C\uDF14     ☁️\n" + "            ☁️ ☁️    \uD83D\uDE80\n" + "   ☁️                *       ☁️ \n" + "                    *  \n" + "      ☁️     * \n" + "               *     \n" + "             * \n" + "            *    \n" + "           *\n" + "         \uD83D\uDCA5\n" + "         \uD83C\uDF0E\n" + " \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80Lets go!",
            "moon soon \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\n" + "☁️☁️ ☁️                  \uD83C\uDF14     ☁️\n" + "            ☁️ ☁️    \uD83D\uDE80\n" + "   ☁️                *       ☁️ \n" + "                    *  \n" + "      ☁️     * \n" + "               *     \n" + "             * \n" + "            *    \n" + "           *\n" + "         \uD83D\uDCA5\n" + "         \uD83C\uDF0E\n" + " \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80Lets go!",
            "moon soon \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\n" + "☁️☁️ ☁️                  \uD83C\uDF14     ☁️\n" + "            ☁️ ☁️    \uD83D\uDE80\n" + "   ☁️                *       ☁️ \n" + "                    *  \n" + "      ☁️     * \n" + "               *     \n" + "             * \n" + "            *    \n" + "           *\n" + "         \uD83D\uDCA5\n" + "         \uD83C\uDF0E\n" + " \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80Lets go!",
            "moon soon \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\n" + "☁️☁️ ☁️                  \uD83C\uDF14     ☁️\n" + "            ☁️ ☁️    \uD83D\uDE80\n" + "   ☁️                *       ☁️ \n" + "                    *  \n" + "      ☁️     * \n" + "               *     \n" + "             * \n" + "            *    \n" + "           *\n" + "         \uD83D\uDCA5\n" + "         \uD83C\uDF0E\n" + " \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80Lets go!",
            "moon soon \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\n" + "☁️☁️ ☁️                  \uD83C\uDF14     ☁️\n" + "            ☁️ ☁️    \uD83D\uDE80\n" + "   ☁️                *       ☁️ \n" + "                    *  \n" + "      ☁️     * \n" + "               *     \n" + "             * \n" + "            *    \n" + "           *\n" + "         \uD83D\uDCA5\n" + "         \uD83C\uDF0E\n" + " \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80Lets go!",
            "moon soon \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\n" + "☁️☁️ ☁️                  \uD83C\uDF14     ☁️\n" + "            ☁️ ☁️    \uD83D\uDE80\n" + "   ☁️                *       ☁️ \n" + "                    *  \n" + "      ☁️     * \n" + "               *     \n" + "             * \n" + "            *    \n" + "           *\n" + "         \uD83D\uDCA5\n" + "         \uD83C\uDF0E\n" + " \uD83D\uDE80\uD83D\uDE80\uD83D\uDE80Lets go!",
            "To the fucking moon guys\uD83D\uDD25","To the fucking moon guys\uD83D\uDD25","To the fucking moon guys\uD83D\uDD25","To the fucking moon guys\uD83D\uDD25",
            "Sure\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF","Sure\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF\uD83D\uDCAF",
            "Don't miss this great project guys","Don't miss this great project guys","Don't miss this great project guys",
            "Hello:(","Hello:(","Hello:(","Hello:(","Hello:(","Hello:(","Hello:(","Hello:(","Hello:(","Hello:(","Hello:(","Hello:(","Hello:(","Hello:(","Hello:(",
            "Don't miss this great project guys","Don't miss this great project guys","Don't miss this great project guys",
            "Hello and welcome","Hello and welcome","Hello and welcome","Hello and welcome","Hello and welcome","Hello and welcome","Hello and welcome","Hello and welcome",
            "Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned","Check pinned",
            "Check pinned","Check pinned","Check pinned",
            "Nice", "Nice work", "Nice team", "Nice project", "Nice community","Nice", "Nice work", "Nice team", "Nice project", "Nice community","Nice", "Nice work", "Nice team", "Nice project", "Nice community",
            "We have come to fly\n" + "To conquer obstacles\n" + "To win now\n" + "Let's go to the moon \uD83C\uDF15\n" + "\uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\uD83D\uDE80\uD83D\uDE80",
            "This is excellent project for the future with strong team, and transparent, planned and great project roadmap. it will be successfully achieved it goals....\uD83D\uDC9E\uD83E\uDD70",
            "LET’s GO","LET’s GO","LET’s GO","LET’s GO","LET’s GO","LET’s GO","LET’s GO","LET’s GO",
            "Hey", "Hey", "Hey", "Hey","Hey", "Hey", "Hey", "Hey","Hey", "Hey", "Hey", "Hey","Hey", "Hey", "Hey", "Hey","Hey", "Hey", "Hey", "Hey","Hey", "Hey", "Hey",
            "Hello:(","Hello:(","Hello:(","Hello:(","Hello:(",
            "Fine",
            "Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate",
            "Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B",
            "Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B","Hello \uD83D\uDC4B",
            "Hi all","Hi all","Hi all","Hi all","Hi all","Hi all",
            "☁️   ☁️    ☁️       \uD83C\uDF14\uD83C\uDF16 ☁️ \uD83D\uDC48\n" +
                    "          ☁️   ☁️     \uD83D\uDE80.       \uD83C\uDF1D\n" +
                    "   ☁️                \uD83D\uDE80*   ☁️ \n" +
                    "                    \uD83D\uDE80*  \n" +
                    "      ☁️       \uD83D\uDE80 * \n" +
                    "               \uD83D\uDE80*     \n" +
                    "             \uD83D\uDE80* \n" +
                    "           \uD83D\uDE80* \n" +
                    "         \uD83D\uDE80 *\n" +
                    "       \uD83D\uDCA5 *\n" +
                    "      \uD83C\uDF0D\n" +
                    " \uD83D\uDE80\uD83D\uDE80Lets go!\uD83D\uDD25",
            "Hi everyone","Hi everyone","Hi everyone","Hi everyone","Hi everyone","Hi everyone","Hi everyone","Hi everyone",
            "Invest and earn more",
            "LOL","LOL","LOL","LOL","LOL",
            "Hi friend","Hi friend","Hi friend","Hi friend","Hi friend","Hi friend","Hi friend","Hi friend",
            "Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes","Yes",
            "Okay","Okay","Okay","Okay","Okay",
            "Exactly","Exactly","Exactly","Exactly","Exactly",
            "Nice project and very very good project","Nice project and very very good project","Nice project and very very good project",
            "How are you",
            "Sure",
            "Hey, how are you doing?","Hey, how are you doing?","Hey, how are you doing?","Hey, how are you doing?","Hey, how are you doing?","Hey, how are you doing?",
            "Ok thanks",
            "Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao",
            "Today is a beautiful day",
            "Excellent","Excellent","Excellent","Excellent",
            "Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate",
            "Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate","Welcome mate",
            "\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25","\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25","\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25",
            "\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25","\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25","\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25",
            "\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25","\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25","\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25\uD83D\uDD25",
            "Hey, how are you doing?","Hey, how are you doing?","Hey, how are you doing?","Hey, how are you doing?","Hey, how are you doing?",
            "Good project","Good project","Good project","Good project","Good project","Good project","Good project",
            "Outstanding",
            "Hlw","Hlw","Hlw","Hlw","Hlw","Hlw","Hlw","Hlw","Hlw","Hlw","Hlw","Hlw","Hlw","Hlw",
            "Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao","Lmao",
            "How is everyone",
            "Now, let's get started!","Now, let's get started!","Now, let's get started!",
            "Lambo \uD83D\uDD1C\uD83D\uDD1C\uD83D\uDD1C\uD83D\uDD1C","Lambo \uD83D\uDD1C\uD83D\uDD1C\uD83D\uDD1C\uD83D\uDD1C",
            "Lambo \uD83D\uDD1C\uD83D\uDD1C\uD83D\uDD1C\uD83D\uDD1C","Lambo \uD83D\uDD1C\uD83D\uDD1C\uD83D\uDD1C\uD83D\uDD1C",
            "Lambo \uD83D\uDD1C\uD83D\uDD1C\uD83D\uDD1C\uD83D\uDD1C","Lambo \uD83D\uDD1C\uD83D\uDD1C\uD83D\uDD1C\uD83D\uDD1C",
            "I hope this project goes to the moon. A very good future is on the way\uD83D\uDE18❤️\uD83D\uDC8B\uD83D\uDE18❤️",
            ""
    };
}
