server:
  port: 8081
spring:
  profiles:
    active: query_route

---
spring:
     cloud:
       gateway:
         routes:
         - id: after_route
           uri: http://httpbin.org:80/get
           predicates:
           - After=2019-04-07T07:00:00.456-11:00[America/Denver]
     profiles: after_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: header_route
        uri: http://httpbin.org:80/get
        predicates:
        - Header=X-Request-Id, \d+
  profiles: header_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: cookie_route
        uri: http://httpbin.org:80/get
        predicates:
        - Cookie=name, zhouzhixiang
  profiles: cookie_route

---
spring:
   cloud:
     gateway:
       routes:
       - id: host_route
         uri: http://httpbin.org:80/get
         predicates:
         - Host=**.zhouzhixiang.com
   profiles: host_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: method_route
        uri: http://httpbin.org:80/get
        predicates:
        - Method=GET
  profiles: method_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: path_route
        uri: http://httpbin.org:80/get
        predicates:
        - Path=/zhouzhixiang/{seg}
  profiles: path_route

---
spring:
  cloud:
    gateway:
      routes:
      - id: query_route
        uri: http://httpbin.org:80/get
        predicates:
        - Query=zhouzhixiang
  profiles: query_route