spring:
  application:
    name: fangjia-eureka-server
  profiles:
    active: master
#  security:
#    user:
#      name: admin
#      password: admin
eureka:
  instance:
    hostname: fangjia-eureka-server
    status-page-url: http://${eureka.instance.hostname}:${server.port}/swagger-ui.html
  client:
    # 由于该应用为注册中心，所以设置为false，代表不向注册中心注册自己
    register-with-eureka: false
    # 由于注册中心的职责就是维护服务实例，他并不需要去检索服务，所以也设置为false
    fetch-registry: false
  server:
    # 关闭自我保护
    enableSelfPreservation: false


